Controllers/User/KhachHangController.cs
using HairSalonRoyalDoan.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using HairSalonRoyalDoan.Models.Dictionary;
using HairSalonRoyalDoan.Controllers.Common;

namespace HairSalonRoyalDoan.Controllers.User
{
    public class KhachHangController : Controller
    {
        KhachHangModel khachHangModel = new KhachHangModel();
         public ActionResult Index()
            {
                return View();
            }

        public static string CreateMD5(string input)
        {
            // GET: KhachHang
           
            // Use input string to calculate MD5 hash
            using (System.Security.Cryptography.MD5 md5 = System.Security.Cryptography.MD5.Create())
            {
                byte[] inputBytes = System.Text.Encoding.ASCII.GetBytes(input);
                byte[] hashBytes = md5.ComputeHash(inputBytes);

                // Convert the byte array to hexadecimal string
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("X2"));
                }
                return sb.ToString();
            }
        }
        public static string refere="1";
        public ActionResult DangNhap()
        {
            refere = Request.UrlReferrer.LocalPath.ToString();
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(string SDTDN, string MatKhauDN)
        {
            
                var MKHash = "";
                if (MatKhauDN!=null)
                {MKHash= CreateMD5(MatKhauDN.ToString());
                }    
                var result = khachHangModel.DangNhap(SDTDN, MKHash);
          
            if (!String.IsNullOrEmpty(result))
            {
                Session.Add(SessionHelper.USER_SESSION, SDTDN);
          
          
                if (refere =="/UserHome/Index")
                {
                    return RedirectToAction("Index", "UserHome");
                }
                else

                {

                    return RedirectToAction("Index", "UserProduct");
                }
            }
            else
            {
              
                    ViewBag.dangnhap = "Tên đăng nhập và mật khẩu không đúng";

                
            }

            
           
              
            return View();

        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View("DangNhap");
        }

        public ActionResult DangXuat()
        {
     
            Session[SessionHelper.CART_SESSION] = null;
            Session[SessionHelper.USER_SESSION] = null;
            Session["SLSP_SESSION"] = null;
            string refere = Request.UrlReferrer.LocalPath.ToString();
            if(refere=="/UserHome/Index")
            {
                
                return RedirectToAction("Index", "UserHome");
            }
            else
            {
            
                return RedirectToAction("Index", "UserProduct");
            }
         
        }

        


        [HttpPost]
        public ActionResult DangKy(Khachhang std)
        {
            string message = std.SDTKH.ToString();
            std.MatKhau = CreateMD5(std.MatKhau.ToString());
           
          string check = new KhachHangModel().CheckInsert(std.SDTKH.ToString());
             
                int cvcheck = Convert.ToInt32(check);
            if (cvcheck == 0)
            {

                khachHangModel.ThemKhachHang(std);
            }
            
            return Json(new { data=cvcheck, JsonRequestBehavior.AllowGet });

        }

       




    }
}

Views/KhachHang/DangNhap.cshtml
@model HairSalonRoyalDoan.Repository.NhanVien


@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DangNhap</title>
    <script src="~/Scripts/Common/Library/jquery-3.4.1.js"></script>
    <style>
        body {
            margin: 0;
            color: #6a6f8c;
            background: #c8c8c8;
            font: 600 16px/18px 'Open Sans',sans-serif;
        }

        *, :after, :before {
            box-sizing: border-box
        }

        .clearfix:after, .clearfix:before {
            content: '';
            display: table
        }

        .clearfix:after {
            clear: both;
            display: block
        }

        a {
            color: inherit;
            text-decoration: none
        }

        .login-wrap {
            width: 100%;
            margin: auto;
            max-width: 525px;
            min-height: 670px;
            position: relative;
            background: url(https://img.freepik.com/free-photo/side-view-man-getting-new-hairstyle_23-2148242799.jpg?size=626&ext=jpg) no-repeat center;
            box-shadow: 0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
        }

        .login-html {
            width: 100%;
            height: 100%;
            position: absolute;
            padding: 90px 70px 50px 70px;
            background: rgba(40,57,101,.9);
        }

            .login-html .sign-in-htm,
            .login-html .sign-up-htm {
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                position: absolute;
                transform: rotateY(180deg);
                backface-visibility: hidden;
                transition: all .4s linear;
            }

            .login-html .sign-in,
            .login-html .sign-up,
            .login-form .group .check {
                display: none;
            }

            .login-html .tab,
            .login-form .group .label,
            .login-form .group .button {
                text-transform: uppercase;
            }

            .login-html .tab {
                font-size: 22px;
                margin-right: 15px;
                padding-bottom: 5px;
                margin: 0 15px 10px 0;
                display: inline-block;
                border-bottom: 2px solid transparent;
            }

            .login-html .sign-in:checked + .tab,
            .login-html .sign-up:checked + .tab {
                color: #fff;
                border-color: #1161ee;
            }

        .login-form {
            min-height: 345px;
            position: relative;
            perspective: 1000px;
            transform-style: preserve-3d;
        }

            .login-form .group {
                margin-bottom: 15px;
            }

                .login-form .group .label,
                .login-form .group .input,
                .login-form .group .button {
                    width: 100%;
                    color: #fff;
                    display: block;
                }

                .login-form .group .input,
                .login-form .group .button {
                    border: none;
                    padding: 15px 20px;
                    border-radius: 25px;
                    background: rgba(255,255,255,.1);
                }

            

                .login-form .group .label {
                    color: #aaa;
                    font-size: 12px;
                }

                .login-form .group .button {
                    background: #1161ee;
                }

                .login-form .group label .icon {
                    width: 15px;
                    height: 15px;
                    border-radius: 2px;
                    position: relative;
                    display: inline-block;
                    background: rgba(255,255,255,.1);
                }

                    .login-form .group label .icon:before,
                    .login-form .group label .icon:after {
                        content: '';
                        width: 10px;
                        height: 2px;
                        background: #fff;
                        position: absolute;
                        transition: all .2s ease-in-out 0s;
                    }

                    .login-form .group label .icon:before {
                        left: 3px;
                        width: 5px;
                        bottom: 6px;
                        transform: scale(0) rotate(0);
                    }

                    .login-form .group label .icon:after {
                        top: 6px;
                        right: 0;
                        transform: scale(0) rotate(0);
                    }

                .login-form .group .check:checked + label {
                    color: #fff;
                }

                    .login-form .group .check:checked + label .icon {
                        background: #1161ee;
                    }

                        .login-form .group .check:checked + label .icon:before {
                            transform: scale(1) rotate(45deg);
                        }

                        .login-form .group .check:checked + label .icon:after {
                            transform: scale(1) rotate(-45deg);
                        }

        .login-html .sign-in:checked + .tab + .sign-up + .tab + .login-form .sign-in-htm {
            transform: rotate(0);
        }

        .login-html .sign-up:checked + .tab + .login-form .sign-up-htm {
            transform: rotate(0);
        }

        .hr {
            height: 2px;
            margin: 60px 0 50px 0;
            background: rgba(255,255,255,.2);
        }

        .foot-lnk {
            text-align: center;
        }
    </style>
</head>
<body>

    <div class="login-wrap">
        <div class="login-html">

            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>

            <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
            <div class="login-form">

                @using (Html.BeginForm("DangNhap", "KhachHang", FormMethod.Post))
                {
                 
                    <div class="sign-in-htm">
                        <div class="group">
                            <label for="user" class="label">Số điện thoại :</label>
                            <input id="SDTDN" required name="SDTDN" type="text" class="input">
                        </div>
                        <div class="group">
                            <label for="pass" class="label">Mật khẩu :</label>
                            <input id="MatKhauDN" required name="MatKhauDN" type="password" class="input" data-type="password">
                        </div>
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"><span class="icon"></span> Keep me Signed in</label>
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Sign In">
                        </div>
                @ViewBag.dangnhap
                        <div class="hr"></div>
                        <div class="foot-lnk">
                            <a href="#forgot">Forgot Password?</a>
                        </div>
                    </div>
                }

          
                 
            <div class="sign-up-htm">
                <div class="group">
                    <label for="user" class="label">Số điện thoại</label>
                    <input id="SoDTKH" required name="SoDTKH" type="text" class="input">
                </div>
                <div class="group">
                    <label for="pass" class="label">Mật Khẩu</label>
                    <input id="MatKhauDK" required name="MatKhauDK" type="password" class="input" data-type="password">
                </div>
                <div class="group">
                    <label for="user" class="label">Email</label>
                    <input id="EmailDK" name="Email" type="email" class="input">
                </div>
                <div class="group">
                    <label for="user" class="label">Địa chỉ</label>
                    <input id="DiaChi" name="DiaChiKH" type="text" class="input">
                </div>

                <div class="group">
                    <label for="pass" class="label">Họ Tên :</label>
                    <input id="HoTenKH" type="text" class="input">
                </div>
                <div class="group">
                    <input type="submit" class="button" id="btnAddkh" value="Sign Up">
                </div>

                <div class="foot-lnk">
                    <label for="tab-1">Already Member?</label>
                </div>
                <div class="foot-lnk">
                    <label for="tab-1"><a href="/UserHome/Index">Trở về trang chủ</a></label>
                </div>
            </div>
                
            </div>
        </div>
    </div>

    <script type="text/javascript">

        document.addEventListener("DOMContentLoaded", function () {
            var elements = document.getElementsByTagName("INPUT");
            for (var i = 0; i < elements.length; i++) {
                elements[i].oninvalid = function (e) {
                    e.target.setCustomValidity("");
                    if (!e.target.validity.valid) {
                        e.target.setCustomValidity("Hãy nhập đầy đủ thông tin ");
                    }
                };
                elements[i].oninput = function (e) {
                    e.target.setCustomValidity("");
                };
            }
        });

     $(function () {
        $("#btnAddkh").click(function () {
            var std = {};
            var check = 0;
            std.HoTenKH = $("#HoTenKH").val();
            std.SDTKH = $("#SoDTKH").val();
            std.Email = $("#EmailDK").val();
            std.DiaChi = $("#DiaChi").val();
            std.MatKhau = $("#MatKhauDK").val();
            var mk_regex =/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$/;
            var vnf_regex = /((09|03|07|08|05)+([0-9]{8})\b)/g;
            var mobile = std.SDTKH;
        
            if (vnf_regex.test(mobile) == false) {
                alert('Số điện thoại của bạn không đúng định dạng!');
                check = 0;
            } else
                if (std.HoTenKH == "" || std.SDTKH == "" || std.Email == "" || std.DiaChi == "" || std.MatKhau == "") {

                    check = 0;
                    alert("Hãy nhập đầy đủ thông tin !");
                }
                else if (mk_regex.test(std.MatKhau) == false) {
                    check = 0;
                    alert("Mật khẩu tối thiểu sáu ký tự, ít nhất một chữ cái và một số")
                }
                else
            {
                        check = 1;
                    }

           
            if (check == 1) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("/DangKy")',
                        data: '{std: ' + JSON.stringify(std) + '}',
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (result) {
                            if (result.data == 0) {
                                alert("Tạo tài khoản thành công !");
                            }
                            else {
                                alert("Số điện thoại đã tồn tại !");
                            }
                      
                        },
                        error: function (errormessage) {
                            alert(errormessage.responseText);
                        }
                    });
         
            }

        });
        });



    </script>


</body>
</html>